// How each personal/outer planet's own territory specifically shows up in
// each house's area of life — a genuine planet-in-house sentence, not the
// house's own generic description reused under every planet that happens to
// sit there. 8 planets × 12 houses = 96 pieces, each written for that exact
// combination.
//
// Sun, Moon and Rising aren't here (see planet-sign-content.ts's same note):
// the big-three section doesn't show a house connection at all, matching how
// the founder's own example laid the page out.

import type { HouseNumber } from "@/features/daily-focus";
import type { SignedPlanet } from "./planet-sign-content";

export const PLANET_IN_HOUSE: Record<SignedPlanet, Record<HouseNumber, string>> = {
  mercury: {
    1: "Here, how you think and communicate becomes part of how you come across from the very first impression.",
    2: "Here, your thinking turns toward money and self-worth — you likely think a lot about what you're worth and how you use what you have.",
    3: "This is a natural fit: your mind is already at home in everyday conversation, learning and the exchange of ideas.",
    4: "Here, your thinking turns inward, toward home and what makes you feel rooted and safe.",
    5: "Here, your mind finds its way into creativity and play — ideas themselves can feel like a form of self-expression.",
    6: "Here, your thinking shows up in your daily habits and how carefully you think through your own routines and health.",
    7: "Here, communication becomes central to how you relate one-to-one — conversation is likely a real part of how you build closeness.",
    8: "Here, your mind is drawn toward what's beneath the surface — the conversations most people avoid having.",
    9: "Here, your thinking naturally reaches for the bigger picture — belief, learning and what's beyond what's familiar.",
    10: "Here, how you think and communicate becomes part of your public role — your ideas are likely part of how you're known.",
    11: "Here, your thinking turns toward community and the future you're building, often through the people and ideas around you.",
    12: "Here, your thinking turns inward and quiet, toward what sits below the surface rather than what's said out loud.",
  },
  venus: {
    1: "Here, love and attraction become part of your sense of self — how you're perceived and how you feel about yourself can be closely linked.",
    2: "This is a natural fit: what you value and what you find beautiful are closely tied to your sense of security.",
    3: "Here, love shows up through everyday connection — closeness often builds through the small, ordinary exchanges.",
    4: "Here, love is closely tied to home and family — what feels beautiful to you is often what feels like belonging.",
    5: "This is a natural fit: love, beauty and creativity all live in the same part of your life here.",
    6: "Here, love shows up in the everyday — through small, practical acts of care rather than grand gestures.",
    7: "This is a natural fit: love and attraction sit right at the centre of how you approach commitment and partnership.",
    8: "Here, love reaches into deeper emotional bonds, where openness and personal space may both matter to you.",
    9: "Here, what you find beautiful is tied to belief and the bigger picture — you may be drawn to people or experiences that expand your worldview.",
    10: "Here, love and attraction become part of your public life — how you're seen may be shaped by charm as much as achievement.",
    11: "Here, love shows up through friendship and community — the people you're drawn to often share your hopes for the future.",
    12: "Here, love turns quiet and private — closeness may come through what's felt rather than what's said.",
  },
  mars: {
    1: "This is a natural fit: your drive is right at the centre of how you show up and assert yourself in the world.",
    2: "Here, your drive turns toward money and self-worth — you likely go after financial security directly rather than waiting for it.",
    3: "Here, your drive shows up through how you speak — you tend to say what you think without much delay.",
    4: "Here, your drive turns toward home and family — you may feel most protective, or most easily provoked, close to home.",
    5: "Here, your drive fuels creativity and play — you go after what excites you with real energy.",
    6: "Here, your drive shows up in your daily habits and how directly you push toward your own health and routine.",
    7: "Here, your drive plays out through your closest relationships — you may bring real energy, or real friction, into partnership.",
    8: "Here, your drive reaches into deeper, more intense territory — you go after what's real rather than what's easy.",
    9: "Here, your drive fuels your beliefs — you go after what you believe in with real conviction.",
    10: "This is a natural fit: your drive is closely tied to your ambitions and what you're building in public.",
    11: "Here, your drive shows up through community — you may push hardest for causes and groups you believe in.",
    12: "Here, your drive turns inward — your energy may show up in private effort rather than anything visible.",
  },
  jupiter: {
    1: "This is a natural fit: growth and opportunity are closely tied to your confidence and sense of self.",
    2: "Here, growth shows up through money and resources — opportunity often arrives in a way that expands what you have.",
    3: "Here, growth comes through learning and conversation — new ideas are often where your opportunities begin.",
    4: "Here, growth is tied to home and family — your sense of security may expand alongside your sense of possibility.",
    5: "This is a natural fit: growth, creativity and joy all live in the same part of your life here.",
    6: "Here, growth shows up in the everyday — small improvements to your routine can add up to something bigger.",
    7: "Here, growth comes through your relationships — partnership is often where real opportunity shows up for you.",
    8: "Here, growth comes through deep change — real transformation, not just incremental improvement.",
    9: "This is a natural fit: growth, belief and the bigger picture are closely tied together for you.",
    10: "Here, growth is tied to your public role — your ambitions and your sense of possibility tend to expand together.",
    11: "This is a natural fit: growth is closely tied to community and the future you're building with other people.",
    12: "Here, growth turns inward — your sense of possibility may expand through rest, reflection or solitude.",
  },
  saturn: {
    1: "This is a natural fit: responsibility is closely tied to your sense of self and how seriously you take showing up.",
    2: "Here, responsibility shows up through money and resources — you likely take your financial security seriously, sometimes more than you need to.",
    3: "Here, responsibility shows up in how you think and communicate — you tend to weigh your words carefully before you say them.",
    4: "Here, responsibility is tied to home and family — you may carry more weight there than anyone's actually asked of you.",
    5: "Here, responsibility shows up around creativity and joy — it can be hard to let play be play without it feeling productive.",
    6: "This is a natural fit: responsibility and daily routine are closely tied together for you.",
    7: "Here, responsibility shows up in your closest relationships — you likely take commitment seriously, sometimes to a fault.",
    8: "Here, responsibility reaches into deeper territory — trust and vulnerability may take real, deliberate effort to build.",
    9: "Here, responsibility shows up in what you believe — you hold your own convictions to a genuinely high standard.",
    10: "This is a natural fit: responsibility is closely tied to your public role and what you're building your career toward.",
    11: "Here, responsibility shows up through community — you may feel a real sense of duty toward the groups you belong to.",
    12: "Here, responsibility turns inward — you may carry weight quietly, in private, rather than showing the effort it takes.",
  },
  uranus: {
    1: "Here, your need for freedom becomes part of your sense of self — you likely resist being defined by anyone else's expectations.",
    2: "Here, freedom shows up around money and resources — your relationship with security may look genuinely different from most people's.",
    3: "Here, freedom shows up in how you think — your ideas are often ahead of, or different from, what's commonly accepted.",
    4: "Here, freedom is tied to home and family — you may define what 'home' means on your own, unconventional terms.",
    5: "Here, freedom fuels creativity — your self-expression is likely original, not built to fit an existing mould.",
    6: "Here, freedom shows up in the everyday — routine may need real room for spontaneity to feel sustainable.",
    7: "Here, freedom shows up in your closest relationships — you likely need connection that doesn't box you in.",
    8: "Here, freedom reaches into deeper territory — real intimacy may need to leave room for independence too.",
    9: "This is a natural fit: freedom and belief are closely tied together — your convictions likely go against the expected answer.",
    10: "Here, freedom shows up in your public life — your path is likely less conventional than the one expected of you.",
    11: "This is a natural fit: freedom is closely tied to community and the future you're building on your own terms.",
    12: "Here, freedom turns inward — you may need real solitude in order to feel like yourself.",
  },
  neptune: {
    1: "Here, imagination becomes part of your sense of self — how you see yourself may be shaped as much by what you imagine as by fact.",
    2: "Here, imagination shows up around money and resources — your relationship with security may be more idealised than practical at times.",
    3: "Here, imagination shows up in how you think and communicate — facts and impressions can blur together in your mind.",
    4: "Here, imagination is tied to home and family — you may idealise what home should feel like more than what it actually is.",
    5: "This is a natural fit: imagination, creativity and joy are closely tied together for you.",
    6: "Here, imagination shows up in the everyday — your routine may need real meaning behind it to feel worth doing.",
    7: "Here, imagination shows up in your closest relationships — you may idealise a partner before you've fully tested the reality.",
    8: "Here, imagination reaches into deeper territory — intimacy can carry a dreamlike, almost otherworldly quality for you.",
    9: "This is a natural fit: imagination and belief are closely tied together — your convictions are often more felt than proven.",
    10: "Here, imagination shows up in your public life — your ambitions may be shaped by a vision that's genuinely hard to put into words.",
    11: "Here, imagination shows up through community — you may be drawn to causes and groups built around a shared ideal.",
    12: "This is a natural fit: imagination and your inner world are closely tied together here.",
  },
  pluto: {
    1: "Here, real transformation becomes part of your sense of self — very little about who you are stays static for long.",
    2: "Here, transformation shows up around money and resources — your relationship with security may go through real, complete shifts over time.",
    3: "Here, transformation shows up in how you think — a belief you once held completely can be replaced by its opposite.",
    4: "Here, transformation is tied to home and family — your sense of roots may be rebuilt more than once in your life.",
    5: "Here, transformation reaches into creativity and joy — what genuinely moves you can shift as deeply as anything else in your life.",
    6: "Here, transformation shows up in the everyday — your habits and routines may go through real, deliberate overhauls, not small tweaks.",
    7: "Here, transformation shows up in your closest relationships — power and trust are likely real, central themes in how you connect.",
    8: "This is a natural fit: transformation is closely tied to intimacy and vulnerability here.",
    9: "Here, transformation shows up in what you believe — your convictions may be tested and rebuilt more than once.",
    10: "Here, transformation shows up in your public life — your career or direction may go through genuine, complete reinvention.",
    11: "Here, transformation shows up through community — your friendships and causes may shift as you do.",
    12: "This is a natural fit: transformation and your inner world are closely tied together here.",
  },
};
